/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_Create_Model */

#ifndef _Included_project_Create_Model
#define _Included_project_Create_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_Create_Model
 * Method:    Make_Model
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_project_Create_1Model_Make_1Model
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     project_Create_Model
 * Method:    Test_Model
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_project_Create_1Model_Test_1Model
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     project_Create_Model
 * Method:    Enable_Camera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_project_Create_1Model_Enable_1Camera
  (JNIEnv *, jobject);

/*
 * Class:     project_Create_Model
 * Method:    Capture_Image
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_project_Create_1Model_Capture_1Image
  (JNIEnv *, jobject);

/*
 * Class:     project_Create_Model
 * Method:    Save_Image
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_project_Create_1Model_Save_1Image
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     project_Create_Model
 * Method:    Face_Make_Model
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_project_Create_1Model_Face_1Make_1Model
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     project_Create_Model
 * Method:    Face_Test_Model
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_project_Create_1Model_Face_1Test_1Model
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
